### ISSUE TITLE
is cc supposed to be working?

### ISSUE THREAD

**Issue by littlemole** [bahamat/docker-unix-1st-ed#1]
trying to compile a simple hello world:

# cat hello.c
include "stdio.h"

void main() {
printf("hello unix\n");
}
# cc hello.c
Can't find /usr/lib/c0
Can't find /usr/lib/c1
I
/tmp/ctm3a?
File not found: /usr/lib/crt0.o
No relocation bits: hello.o

apparently there is no /usr/lib ...

anyway you absolutely made my day :-)

**Comment by bahamat** [comment]
Nope. First Edition UNIX was written primarily in assembly and BCPL. The C compiler wasn't featured until Second Edition, so it's not surprising that it's there, but doesn't work. Unix itself wasn't rewritten in C until 4th Edition.

**Comment by Keith-S-Thompson** [comment]
I ran into this as well.

It seems odd that there's no `/usr` directory.

The Bell Labs man pages at https://www.bell-labs.com/usr/dmr/www/man11.pdf indicate that the B compiler can be invoked with
```
sh rc /usr/b/rc name
```
which of course doesn't work.

Is there a way to compile *anything* with this system? There seems to be a lot of stuff missing; is it missing from the Docker image, or missing because this version of Unix just didn't have it yet?

(NOTE: I am **not** complaining, just trying to figure out whether there's more I can do with this thing.)

**Comment by bahamat** [comment]
Hi @Keith-S-Thompson,

Thanks for your interest, but really all I did was dockerize this. And it's not really a docker image of 1st Edition Unix. It's a docker image of Ubuntu that runs simvh, a PDP emulator. The virtual image running in the emulator comes from [c3x04/Unix-1st-Edition-jun72](https://github.com/c3x04/Unix-1st-Edition-jun72).

I did this only for a demo so it's not something I ever intended to keep in working order, and as far as what "should" be working, I never used a 1st edition Unix to have a frame of reference. The intent was never to have a "functional" (whatever that would mean) 1st Edition Unix system.

However, there doesn't exist a complete working 1st Edition Unix system anywhere, so far as I know. There are parts known to be missing. The reference image used here is from June 1972, and the 1st Edition manual is dated 1971. So there's definitely some delta here.

I also know that early Unix was cross-compiled on another system and installed onto the PDP. So this image well may be accurate.
